### ISSUE TITLE
Multi Day select

### ISSUE THREAD

**Issue by jbirch8865** [wakirin/Lightpick#100] opened 2019-10-26 06:07 UTC
I read through the issues list and apologize if this has been asked or addressed in the past.  But does this Calendar have the ability to have multiple days selected that are not in a range?  Like if I want to "unselect" Tuesday after selecting Sunday through Saturday is that possible?

Thank you

**Comment by wakirin** [comment] 2019-10-26 13:08
Duplicate of #93

**Closed by wakirin** 2019-10-26 13:08 UTC
