### ISSUE TITLE
how to add time dropdown

### ISSUE THREAD

**Issue by masteroftrix** [wakirin/Lightpick#97] opened 2019-10-23 13:37 UTC
Hello sir if want to add time picker or time drop down in Lightpick how can i add to your calendar.
please solve my problem as soon as possible

![image](https://user-images.githubusercontent.com/38158655/67398294-defc1100-f5c3-11e9-8d4f-5924c0a630fe.png)

**Comment by wakirin** [comment] 2019-10-25 16:07
Duplicate of #45

**Closed by wakirin** 2019-10-25 16:07 UTC
